/**
 * Solution D: Multi-Resolution Downsampling Benchmark.
 *
 * Compares two strategies for step-based downsampling queries:
 *   1. SINGLE-RES:  Read full-resolution TsFile, decode ALL values, take 1/step
 *   2. MULTI-RES:   Route to smallest resolution >= step, read & decode fewer values
 *
 * Routing logic:
 *   step <= 1    → L0 (full res)
 *   step <= 10   → L10 (10x downsampled) → take every (step/10)-th
 *   step <= 100  → L100 (100x downsampled) → take every (step/100)-th
 *   step > 100   → L100 → take every (step/100)-th
 *
 * Requires multi-resolution TsFile generated by MultiResTsFileBuilder.
 *
 * Usage: java -Xmx1g -cp <classpath> MultiResBenchmark <multi_res_dir> <orig_dir>
 */

import org.apache.tsfile.enums.TSDataType;
import org.apache.tsfile.file.metadata.IDeviceID;
import org.apache.tsfile.read.TsFileSequenceReader;
import org.apache.tsfile.read.TsFileReader;
import org.apache.tsfile.read.common.Path;
import org.apache.tsfile.read.expression.QueryExpression;
import org.apache.tsfile.read.expression.impl.GlobalTimeExpression;
import org.apache.tsfile.read.filter.factory.FilterFactory;
import org.apache.tsfile.read.filter.factory.TimeFilterApi;
import org.apache.tsfile.read.query.dataset.QueryDataSet;

import java.io.*;
import java.util.*;

public class MultiResBenchmark {

    static final int[] STEP_SIZES = {2, 5, 10, 50, 100, 500};
    static final int N_WARMUP = 5;
    static final int N_MEASURE = 10;

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("Usage: java MultiResBenchmark <multi_res_dir> <orig_dir>");
            System.exit(1);
        }

        File multiDir = new File(args[0]);
        File origDir = new File(args[1]);

        // Find matching device files
        File[] multiFiles = multiDir.listFiles((f, n) -> n.endsWith("_L0.tsfile"));
        File[] origFiles = origDir.listFiles((f, n) -> n.endsWith(".tsfile")
                && !n.contains("_L"));
        if (multiFiles == null || multiFiles.length == 0
                || origFiles == null || origFiles.length == 0) {
            System.err.println("No matching files");
            return;
        }
        Arrays.sort(multiFiles);
        Arrays.sort(origFiles);

        // Use first device
        String devName = multiFiles[0].getName().replace("_L0.tsfile", "");
        String l0Path = multiFiles[0].getAbsolutePath();
        String l10Path = l0Path.replace("_L0.tsfile", "_L10.tsfile");
        String l100Path = l0Path.replace("_L0.tsfile", "_L100.tsfile");
        String origPath = origFiles[0].getAbsolutePath();

        // Discover measurements and device path from ORIGINAL file
        TsFileSequenceReader r0orig = new TsFileSequenceReader(origPath);
        IDeviceID devOrig = r0orig.getAllDevices().get(0);
        String devicePath = devOrig.toString();
        Map<String, TSDataType> measMapOrig = r0orig.getMeasurement(devOrig);
        // Skip empty key (time column in aligned mode)
        String meas = null;
        for (String k : measMapOrig.keySet()) {
            if (k != null && !k.isEmpty()) { meas = k; break; }
        }
        if (meas == null) meas = measMapOrig.keySet().iterator().next();
        r0orig.close();

        // Get total points: use metadata from original file
        int n0 = countTotal(origPath, devicePath, meas);
        int n10 = n0 / 10;
        int n100 = n0 / 100;

        long origSize = new File(origPath).length();
        long l0Size = new File(l0Path).length();
        long l10Size = new File(l10Path).length();
        long l100Size = new File(l100Path).length();
        long totalMultiSize = l0Size + l10Size + l100Size;

        System.out.println("{");
        System.out.println(" \"device\":\"" + devName + "\",");
        System.out.println(" \"measurement\":\"" + meas + "\",");
        System.out.println(" \"points\": {");
        System.out.println("   \"L0\":" + n0 + ",");
        System.out.println("   \"L10\":" + n10 + ",");
        System.out.println("   \"L100\":" + n100);
        System.out.println(" },");
        System.out.println(" \"sizes\": {");
        System.out.println("   \"original\":" + origSize + ",");
        System.out.println("   \"L0\":" + l0Size + ",");
        System.out.println("   \"L10\":" + l10Size + ",");
        System.out.println("   \"L100\":" + l100Size + ",");
        System.out.println("   \"total_multi\":" + totalMultiSize + ",");
        System.out.println("   \"overhead_pct\":" + String.format("%.1f",
                100.0 * (totalMultiSize - origSize) / origSize));
        System.out.println(" },");

        // ---- Benchmark ----
        System.out.println(" \"results\": [");

        for (int si = 0; si < STEP_SIZES.length; si++) {
            int step = STEP_SIZES[si];

            // Route to appropriate level
            String levelPath;
            String levelName;
            int levelN;
            int levelStep; // step within this level

            if (step <= 1) { levelPath = l0Path; levelName = "L0"; levelN = n0; levelStep = 1; }
            else if (step <= 10) { levelPath = l10Path; levelName = "L10"; levelN = n10; levelStep = Math.max(1, step / 10); }
            else { levelPath = l100Path; levelName = "L100"; levelN = n100; levelStep = Math.max(1, step / 100); }

            long levelFileSize = new File(levelPath).length();
            int expectedTargets = n0 / step;

            // --- Single-res: query original, iterate ALL, count 1/step ---
            TsFileSequenceReader seqOrig = new TsFileSequenceReader(origPath);
            TsFileReader tsOrig = new TsFileReader(seqOrig);
            Path pOrig = new Path(devicePath, meas, true);
            var tfOrig = FilterFactory.and(
                    TimeFilterApi.gtEq(0L), TimeFilterApi.ltEq(Long.MAX_VALUE));
            var exprOrig = QueryExpression.create(
                    Collections.singletonList(pOrig), new GlobalTimeExpression(tfOrig));

            for (int w = 0; w < N_WARMUP; w++) {
                var ds = tsOrig.query(exprOrig);
                int cnt = 0, stepCnt = 0;
                while (ds.hasNext()) { ds.next(); if (cnt % step == 0) stepCnt++; cnt++; }
            }
            tsOrig.close(); seqOrig.close();
            System.gc();

            long t0 = System.nanoTime();
            int totalFull = 0, usefulFull = 0;
            for (int m = 0; m < N_MEASURE; m++) {
                TsFileSequenceReader seq = new TsFileSequenceReader(origPath);
                TsFileReader ts = new TsFileReader(seq);
                var ds = ts.query(exprOrig);
                int cnt = 0, sc = 0;
                while (ds.hasNext()) { ds.next(); if (cnt % step == 0) sc++; cnt++; }
                totalFull += cnt;
                usefulFull += sc;
                ts.close(); seq.close();
            }
            long fullNs = (System.nanoTime() - t0) / N_MEASURE;
            long usefulFullAvg = usefulFull / N_MEASURE;

            // --- Multi-res: query appropriate level, iterate and sample ---
            for (int w = 0; w < N_WARMUP; w++) {
                TsFileSequenceReader seq = new TsFileSequenceReader(levelPath);
                TsFileReader ts = new TsFileReader(seq);
                var ds = ts.query(QueryExpression.create(
                        Collections.singletonList(new Path(devicePath, meas, true)),
                        new GlobalTimeExpression(tfOrig)));
                int cnt = 0;
                while (ds.hasNext()) { ds.next(); cnt++; }
                ts.close(); seq.close();
            }
            System.gc();

            long t1 = System.nanoTime();
            int totalMulti = 0, usefulMulti = 0;
            for (int m = 0; m < N_MEASURE; m++) {
                TsFileSequenceReader seq = new TsFileSequenceReader(levelPath);
                TsFileReader ts = new TsFileReader(seq);
                var ds = ts.query(QueryExpression.create(
                        Collections.singletonList(new Path(devicePath, meas, true)),
                        new GlobalTimeExpression(tfOrig)));
                int cnt = 0, sc = 0;
                while (ds.hasNext()) { ds.next(); if (cnt % levelStep == 0) sc++; cnt++; }
                totalMulti += cnt;
                usefulMulti += sc;
                ts.close(); seq.close();
            }
            long multiNs = (System.nanoTime() - t1) / N_MEASURE;
            long totalMultiAvg = totalMulti / N_MEASURE;
            long usefulMultiAvg = usefulMulti / N_MEASURE;

            // Read amplification
            long usefulBytes = Math.max(usefulFullAvg, 1) * 16;
            double singleAmp = (double) origSize / usefulBytes;
            double multiAmp = (double) levelFileSize / usefulBytes;

            double speedup = multiNs > 0 ? (double) fullNs / Math.max(multiNs, 1) : 0;

            if (si > 0) System.out.println(",");
            System.out.println("  {");
            System.out.println("   \"step\":" + step + ",");
            System.out.println("   \"level\":\"" + levelName + "\",");
            System.out.println("   \"level_step\":" + levelStep + ",");
            System.out.println("   \"level_points\":" + levelN + ",");
            System.out.println("   \"level_file_bytes\":" + levelFileSize + ",");
            System.out.println("   \"target_count\":" + expectedTargets + ",");
            System.out.println("   \"single_full_ns\":" + fullNs + ",");
            System.out.println("   \"multi_ns\":" + multiNs + ",");
            System.out.println("   \"speedup\":" + String.format("%.1f", speedup) + ",");
            System.out.println("   \"single_decoded\":" + (totalFull / N_MEASURE) + ",");
            System.out.println("   \"multi_decoded\":" + totalMultiAvg + ",");
            System.out.println("   \"decode_reduction_pct\":" +
                    String.format("%.1f", 100.0 * (n0 - totalMultiAvg) / n0) + ",");
            System.out.println("   \"single_useful\":" + usefulFullAvg + ",");
            System.out.println("   \"multi_useful\":" + usefulMultiAvg + ",");
            System.out.println("   \"single_read_amp\":" + String.format("%.1f", singleAmp) + ",");
            System.out.println("   \"multi_read_amp\":" + String.format("%.1f", multiAmp) + ",");
            System.out.println("   \"amp_improvement_pct\":" +
                    String.format("%.1f", singleAmp > 0
                            ? 100.0 * (singleAmp - multiAmp) / singleAmp : 0));
            System.out.print("  }");
        }
        System.out.println("\n ]");
        System.out.println("}");
    }

    static int countTotal(String path, String device, String meas) throws Exception {
        TsFileSequenceReader r = new TsFileSequenceReader(path);
        List<org.apache.tsfile.file.metadata.ChunkMetadata> metas =
                r.getChunkMetadataList(r.getAllDevices().get(0), meas, true);
        int total = 0;
        for (var cm : metas) total += (int) cm.getNumOfPoints();
        r.close();
        return total;
    }
}
